on: [workflow_dispatch]

name: Render Report

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
 
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
               any::knitr
               any::rmarkdown
               any::dplyr
               any::tidyr
               any::ggplot2
               any::lubridate
               any::googleway
               any::purrr
               any::leaflet
               any::gepaf
               any::tidyverse
               any::gt
               any::gepaf
               any::paletteer
               any::plotly
               any::flexdashboard
               any::ggthemes
               any::sf
               any::tidycensus
               any::gepaf
               any::osmdata
               any::gepaf
               any::tigris
               any::gepaf
               any::ggridges
               any::gtExtras
               any::gepaf
               any::plotly
               any::ggmap
               any::viridis
               any::haven
               any::htmltools        
      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        env:
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        with:
          to: html
          path: Assignment_8_Map.qmd
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
